version: '3'

services:
  jwt-validator:
    build:
      context: .
      dockerfile: Dockerfile
    image: jwt-validator
    container_name: jwt-validator
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m

  prometheus:
    image: 'prom/prometheus:v2.14.0'
    ports:
      - '9090:9090'
    command: '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'

  grafana:
    image: 'grafana/grafana:6.5.0'
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
