global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - "jwt-validator:8080"