replicaCount: 3

image:
  repository: talthur/jwt-validator
  pullPolicy: Always
  tag: latest

serviceAccount:
  create: true
  automount: true

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

ingress:
  enabled: false
  annotations: {}
  tls: []

tolerations: []

affinity: {}
